---
- name: Test playbook
  hosts: test

  tasks:
    
  - name: Docker nginx container
    shell: sudo docker run -dit --name nginx -p 85:80 nginx:latest
  
  - name: Check web server
    shell: curl localhost:85
    register: output
   
  - name: Show curl output willya
    debug:
      var: output.stdout
